sudo: false

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install tox flake8

script:
  - flake8 refunite_drc_admin tests
  - tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d .)

notifications:
    on_success: never
